### ISSUE TITLE
1.3.0 doesn't work on Ubuntu Android machines

### ISSUE THREAD

**Issue by atomicelliot** [mobile-dev-inc/bitrise-step-maestro-cloud-upload#6] opened 2023-10-25 16:32 UTC
I'm getting the following error:
`curl: option --retry-all-errors: is unknown`

Bitrise has curl 7.68.0 installed which doesn't have that option

**Comment by artem888** [comment] 2023-10-30 16:05
hey @atomicelliot ! the issue is fixed within latest maestro cloud upload step version (1.3.2)

**Closed as completed** 2023-10-30 16:05 UTC
